version: 2
jobs:
  maven/test:
    docker:
      - image: circleci/openjdk:11-jdk-node
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
      - restore_cache:
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline --settings 'pom.xml'
      - run:
          name: Run Tests
          command: mvn verify --settings 'pom.xml'
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_test_results:
          path: core-service/target/surefire-reports
      - run:
          name: Build
          command: mvn package -DskipTests=true
      - store_artifacts:
          paths:
            - core-service/target/core.jar
            - infra-service/target/core.jar
  deploy:
    machine:
      enabled: true
    - steps:
      - run:
        name: Generate Cache Checksum
        command: echo 'Deploy!!!'

workflows:
  maven_test:
    jobs:
      - maven/test
      - deploy:
        requires:
          - maven/test
        filters:
          branches:
            only: circleci-project-setup
  version: 2