version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
      - restore_cache:
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline --settings 'pom.xml'
      - run:
          name: Run Tests
          command: mvn verify --settings 'pom.xml'
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_test_results:
          path: core-service/target/surefire-reports
      - run:
          name: Build
          command: mvn package -DskipTests=true
      - store_artifacts:
          path: core-service/target/core.jar
      - store_artifacts:
          path: infra-service/target/infra.jar
      - store_artifacts:
          path: service
      - persist_to_workspace:
          root: ~/repo
          paths:
            - core-service/target
            - infra-service/target
            - service
  deploy:
    machine: true
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
          - "36:3d:62:07:50:47:68:a5:f2:95:90:61:53:55:53:8e"
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy core-service
          command: scp -r core-service/target/*.jar $DEPLOY_USER@$DEPLOY_NODE:/home/$DEPLOY_USER/blog_deploy
      - run:
          name: Deploy infra-service
          command: scp -r infra-service/target/*.jar $DEPLOY_USER@$DEPLOY_NODE:/home/$DEPLOY_USER/blog_deploy
      - run:
          name: Deploy scripts
          command: scp -r service/*.* $DEPLOY_USER@$DEPLOY_NODE:/home/$DEPLOY_USER/blog_deploy/service
      - run:
          name: Start infra-service
          command: ssh $DEPLOY_USER@$DEPLOY_NODE "service infra restart"
workflows:
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
  version: 2